default_language_version:
  python: python3.10.13

default_stages: [pre-commit]

fail_fast: True

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-xml
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args:
          - --maxkb=300
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: debug-statements
      - id: check-executables-have-shebangs

  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.1
    hooks:
      - id: poetry-check
        files: pyproject.toml

      - id: poetry-lock
        files: pyproject.toml
        args:
          - --check

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - --profile=black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --extend-ignore=E203,E704
        additional_dependencies:
          - flake8-bugbear==23.12.2

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.6"
    hooks:
      - id: bandit
        args:
          - --skip=B101
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==23.12.1]
      - id: nbqa-isort
        additional_dependencies: [isort==5.13.2]
      - id: nbqa-flake8
        additional_dependencies: [flake8==6.1.0]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [markdown, yaml, toml, json, dockerfile, shell]
        args:
          - --print-width=80
          - --prose-wrap=always
